version: "3.9"
services:

    efb:
        container_name: efb
        image: xzsk2/efb-docker:latest
        restart: unless-stopped
        volumes:
            - ./efb:/app/config
        networks:
            efbm:
                aliases:
                    - efb
        depends_on:
            - mirai
    
    mirai:
        container_name: mirai
        image: xzsk2/mirai-docker:latest
        restart: unless-stopped
        volumes:
            - ./mirai/config:/app/config
            - ./mirai/bots:/app/bots
        networks:
            efbm:
                aliases:
                    - mirai

networks:
    efbm: 